### ISSUE TITLE
Fix long text strings breaking mobile view

### ISSUE THREAD

**Issue by danjamescrosby** [kurrent-io/documentation#134]
Two pages have come up with mobile usability errors on Google Search Console. Looking at it, the cause is long strings of text with no breaks in - they break the 100% width and the screen has horizontal scroll bar.

Pages affected are:

- https://developers.eventstore.com/clients/dotnet/5.0/reference/eventstore.client.streams.html
- https://developers.eventstore.com/clients/dotnet/5.0/reference/eventstore.client.html

Example text: "Operator: EventStore.Client.HashCode.op_Implicit(EventStore.Client.HashCode)~System.Int32"

Fix could either be to wrap these long strings in code blocks or an improvement to the CSS to allow breaks of long words.

**Comment by alexeyzimarev** [comment]
That's expected since those pages are very big. These are API reference pages and until I change my tool to structure the output differently, we can't do much about it.

**Comment by danjamescrosby** [comment]
Ah I see. On the main site I added the following CSS to try and counter it if it does occur. It just allows the string to break on to a new line if it overflows. Not a high priority thing but I can test it locally on the docs and see if it works at some point

```
 p, span, li, code {
    overflow-wrap: break-word;
}
```

**Comment by mat-mcloughlin** [comment]
Closing as fixed by new design
