### ISSUE TITLE
Intermittent issue with Vuepress redirects

### ISSUE THREAD

**Issue by danjamescrosby** [kurrent-io/documentation#138]
The redirect for `/latest.html` seems to intermittently fail and results in 404s for the Getting Started links. Been reported via the chat and I've tested and confirmed it.

**Comment by alexeyzimarev** [comment]
@danjamescrosby it' actually dynamic and done in code. And it works for me. It only stops working when the new version is deployed when you are still looking at it, and the URL changes. You can look now and it actually works. I have not seen an issue with this for a while.

**Comment by danjamescrosby** [comment]
@alexeyzimarev it's not working for me still now. And if you put the URL in here it returns a 404 error: https://www.redirect-checker.org/index.php 

Screenshot:
![image](https://user-images.githubusercontent.com/57628772/99426808-8731f580-28fc-11eb-882a-401d391f8669.png)

**Comment by alexeyzimarev** [comment]
Ok, it's because the router is configured when the Vue app initialises. Why can't we point to `https://developers.eventstore.com`? It has the latest docs updates and a big button :)
