### ISSUE TITLE
20.6.1 new connection settings for TCP client

### ISSUE THREAD

**Issue by alexeyzimarev** [kurrent-io/documentation#142]
## New and changed connection settings for TCP client in v20.6.x since v5

- An option to skip certificate validation on HTTP requests such as cluster discovery or projections manager has been added. The only option is `SkipCertificateValidation`.

```
CustomHttpMessageHandler=SkipCertificateValidation
```

- New options for setting up gossip seeds, the schema can now be (optionally) specified and it now supports host names:

```
GossipSeeds=http://127.0.0.1:2112
GossipSeeds=https://127.0.0.1:2112
GossipSeeds=127.0.0.1:2112
GossipSeeds=https://node1.eventstore:2112
```

### Not available in connection string:

- `PreferReadOnlyReplica()`
- `DisableTls` replaces `UseSslConnection`
- `DisableServerCertificateValidation` has been added to disable cert validation on TCP requests. Previously this was specified as an option in `UseSslConnection`.

**Comment by ylorph** [comment]
Need to check in current documentation
