### ISSUE TITLE
Environment variable for setting gossip interval is missing GOSSIP

### ISSUE THREAD

**Issue by johnnycederholm** [kurrent-io/documentation#143]
According to the section about configure the gossip interval for Event Store v5 it states that using EVENTSTORE_INTERVAL_MS would change the interval. Setting this wouldn't have any effect, but EVENTSTORE_GOSSIP_INTERVAL_MS works.

The section I refering to is this, https://developers.eventstore.com/server/5.0.8/server/clustering/gossip.html#gossip-interval.

**Comment by alexeyzimarev** [comment]
Thanks! Copy-paste issue :)
