### ISSUE TITLE
API reference is in the wrong place

### ISSUE THREAD

**Issue by alexeyzimarev** [kurrent-io/documentation#157]
We have the gRPC client API reference in the v5 docs, which is entirely wrong.

Quick fix is to re-generate the API reference manually and put it to the correct place.

**Comment by alexeyzimarev** [comment]
I temporarily removed the API reference as it's confusing. We'll need to generate and put it back.

**Comment by oskardudycz** [comment]
@alexeyzimarev could you clarify if we need to do something around that?

**Comment by mat-mcloughlin** [comment]
closing for #338
