### ISSUE TITLE
Consider removing the requirement of having WSL for Windows users

### ISSUE THREAD

**Issue by oskardudycz** [kurrent-io/documentation#164]
Currently, we're using [sed](https://www.gnu.org/software/sed/manual/sed.html) internally for building our docs. Because of that for Windows users, it's needed to have WSL2 configured. It's not installed by default and [instruction](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is a bit complex. It may discourage some of the potential contributors for sending docs updates.

It's not the top priority, as they can send PR without running it locally, but I believe that at some point it'd be worth considering that.

See more in #163

**Comment by alexeyzimarev** [comment]
I think we don't have to remove it as it is only used to build the docs. What we should do is to ignore the import if the source isn't there.

**Comment by oskardudycz** [comment]
@alexeyzimarev I'm fine with ignoring the import 👍 However, I think that it would be good to be able to also (eventually) import without WSL.
