### ISSUE TITLE
Use real-world event and stream names etc. in quick start guide

### ISSUE THREAD

**Issue by oskardudycz** [kurrent-io/documentation#167]
I think that using more real-world names of the events and streams (than eg. [some-event](https://github.com/EventStore/EventStore-Client-Dotnet/blob/initial-docs/docs/samples/quick-start/Program.cs#L26), [testEvent](https://github.com/EventStore/EventStore-Client-Dotnet/blob/initial-docs/docs/samples/quick-start/Program.cs#L26), [testStream](https://github.com/EventStore/documentation/blob/master/samples/grpc/dotnet/GrpcDocs/Producer.cs#L32)) would help to better understand both event sourcing and the usage context in Event Store.

I think that if we agreed on the business case (eg. cinema tickets reservation, e-commerce order) in samples and be consistent on it then we could cut the learning curve.

**Comment by mat-mcloughlin** [comment]
We've talked about this in the past but never come to a conclusion. I've always found it difficult to find a balance between a domain that is complex enough to require DDD/CQRS/ES and one that is simple enough to not distract from the message

I'm open to suggestions

**Comment by oskardudycz** [comment]
I can say that when I'm looking at those samples then even that I know what are they're doing then I'm not sure what exact parameter means. Maybe Orders would be good? Event though it's boring and played, it's understood well and anyone can imagine how it works.

**Comment by mat-mcloughlin** [comment]
I like the idea of cinema reservation as that will allow for some more complicated scenarios around consistency

**Comment by alexeyzimarev** [comment]
Yeah, I have some code from the DDD EU workshop. The domain seems simple but appears to be quite complex.

**Comment by oskardudycz** [comment]
Yup, there are a lot of edge cases, but we don't need to cover all possible scenarios. We could treat it as the background and use jut a subset of the domain.
