### ISSUE TITLE
More info about projection from category

### ISSUE THREAD

**Issue by lkurzyniec** [kurrent-io/documentation#173]
I needed to find out this topic on stackoverflow to get to know how categories works. It should be in eventstore docs.
https://stackoverflow.com/questions/24057466/how-to-do-projection-from-a-category

**Comment by alexeyzimarev** [comment]
@lkurzyniec could you provide a bit more information about what you haven't been able to find? Because the issue described in that SO question is documented: https://developers.eventstore.com/server/5.0.8/server/projections/system-projections.html#by-category

**Comment by lkurzyniec** [comment]
Found it ;)
https://developers.eventstore.com/server/20.6/server/projections/system-projections.html#by-category
