### ISSUE TITLE
Rename "Writing" to "Appending" throughout documentation

### ISSUE THREAD

**Issue by oskardudycz** [kurrent-io/documentation#180]
For some reason, we're not consistent and using "writing" instead of "appending" in many places in our documentation.

**Comment by alexeyzimarev** [comment]
Is it a problem? It is a good practice to use synonyms, the text looks weird when the same word appears many times.

**Comment by oskardudycz** [comment]
I think that's good if it's used as a synonym, but all menus etc. are using "writing". I think that append is more correct (especially that our API methods are also named as such). My suggestion is to use `appending` as the main/suggested word and `writing` when we need to use a synonym.
