### ISSUE TITLE
all gRPC clients do not retry any commands by default, differing from the TCP client approach

### ISSUE THREAD

**Issue by condron** [kurrent-io/documentation#189]

**Comment by hayley-jean** [comment]
The approach to retries should be application-specific.

Client code doesn't have to do anything specific to deal with reconnections or selecting a new node to connect to. This is done automatically by the gRPC client.
If a reconnection is needed, then the correct node will be selected the next time any request is run.

For example, if you were to try and append to a stream and the leader node is down, the request will time out.
If your code were to retry that request, the gRPC client will automatically connect to a new leader and should succeed.

**Comment by mat-mcloughlin** [comment]
We are going to write an article on this https://github.com/EventStore/blog-articles/issues/91
