### ISSUE TITLE
EventStore Cloud: Add drawing of networking

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#193]
a small drawing of how the networking looks like would be helpful 
Especiallywhen setting up Tailscale

**Comment by ylorph** [comment]
Here's a sample 


![ES-cloud-Networking-202101](https://user-images.githubusercontent.com/10076395/104563437-ef296180-5649-11eb-9c44-da5eda8d5681.png)

I'd make 2 drawings out of it with & without tailscale.

**Comment by ylorph** [comment]
**2 Questions to Zachary:**
- What do we use as DNS services for the cloud products, Route 53 for all supported cloud ?
- Is the Tailscale setup, and later when we provide it oob ,  meant to enable customers to use our  cloud offering with on-prem apps & other clouds ? 
**Anwsers:**
- We utilize Route53 for DNS names
- TailScale will be the first cross connect resource meant to support desktop -> cluster access
- We will evaluate and add more cross connect options in the future which may allow cross cloud provider connectivity (edited)

**Comment by ylorph** [comment]
@sigil66 ,thinking about adding such kind of drawing to de EventStore Cloud documentation to illustrate the networking 
 do those make sense to you ?
![EsCloudNetworking](https://user-images.githubusercontent.com/10076395/105134865-597d4e80-5aef-11eb-9780-5c354f6a156b.png)

**Comment by Pouncy** [comment]
Hey @ylorph here are the diagrams. Wasn't sure if you needed them split into 2 or not so I've provided both. Let me know if you'd like any changes. 
[SVGs.zip](https://github.com/EventStore/documentation/files/5893477/SVGs.zip)

**Comment by ylorph** [comment]
> 
> 
> Hey @ylorph here are the diagrams. Wasn't sure if you needed them split into 2 or not so I've provided both. Let me know if you'd like any changes.
> [SVGs.zip](https://github.com/EventStore/documentation/files/5893477/SVGs.zip)

Perfect @Pouncy thnks , I'll add them Wednesday to the doc
