### ISSUE TITLE
Event Store Cloud: Add nslookup check after Provisioning

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#194]
problem: some ISP don't resolve xxxx.mesdb.eventstore.cloud
Add a way for users to easily check / troubleshoot that the hosted cluster is discoverable 
If the lookup fails document or suggest the workaround of DNS server change 
something like 

```
nslookup bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
*** Can't find bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud: No answer

nslookup bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.4
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.6
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.5

```

**Comment by discount-elf** [comment]
That doesn't look like an ISP is not resolving it. That looks like some sort of security feature on the router that filter responses that contain private address ranges. Alternatively the router may do local resolution and may not have the hints for the .cloud root, however if that was the case you would not be able to access the console.

**Comment by mat-mcloughlin** [comment]
closing in favour of #245
