### ISSUE TITLE
Clarify  Backup order

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#230]
! the pull request is in the EventStore Repo : https://github.com/EventStore/EventStore/pull/2858

backup indexes
backup *.chk
backup chunks

https://developers.eventstore.com/server/v20/server/operations/database-backup.html#backing-up-a-database
https://developers.eventstore.com/server/v5/server/operations/database-backup.html

**Comment by ylorph** [comment]
- [ ]  Check with support system for the complete procedure

**Comment by condron** [comment]
Proposed Backup Process
1) Diff existing files Between Backup and Source
2) Mark for removal any Chunk or Index
files in backup that are not also in Source.
3) Copy the Index Map to backup
4) Copy all non-writer checkpoints
5) Copy writer Checkpoint
6) Mark for copy All Chunk & Index Files in source
7) Copy all marked for copy files in source, skipping matching files in backup.
8) Delete all marked for removal files in backup. (edited)

**Comment by mat-mcloughlin** [comment]
Can we just confirm that this will close #130

**Comment by condron** [comment]
Yes, this should close #130 as well
