### ISSUE TITLE
HTTP API docs for the v20 server

### ISSUE THREAD

**Issue by alexeyzimarev** [kurrent-io/documentation#240]
- Do not touch the existing v5 HTTP API docs
- Include HTTP API endpoints to v20 server docs like it's done in diagnostics and scavenge for
  - Config reload (Configuration section)
  - Switch the leader (Node roles? Also good for Scavenge) - this needs clarification as it's not documented

- Serverside filtering
Can we get a swagger file for v20 HTTP API generated docs?

**Comment by mat-mcloughlin** [comment]
We should only document the management functionality of v20 +

**Comment by ylorph** [comment]
Will do with the move of http docs in the servers
