### ISSUE TITLE
FAQ Page for the cloud

### ISSUE THREAD

**Issue by mat-mcloughlin** [kurrent-io/documentation#245]
DNS issues

**Comment by mat-mcloughlin** [comment]
problem: some ISP don't resolve xxxx.mesdb.eventstore.cloud
Add a way for users to easily check / troubleshoot that the hosted cluster is discoverable
If the lookup fails document or suggest the workaround of DNS server change
something like

nslookup bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
*** Can't find bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud: No answer

nslookup bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.4
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.6
Name:   bvu5ogirh41u2p2pl8q0.mesdb.eventstore.cloud
Address: 172.23.0.5

Zach: That doesn't look like an ISP is not resolving it. That looks like some sort of security feature on the router that filter responses that contain private address ranges. Alternatively the router may do local resolution and may not have the hints for the .cloud root, however if that was the case you would not be able to access the console.

**Comment by mat-mcloughlin** [comment]
Becci has been working on an FAQ from the questions that have already been asked. That would be a good starting place

**Comment by ylorph** [comment]
>problem: some ISP don't resolve xxxx.mesdb.eventstore.cloud

made some further testing : they block the answer of external DNS queries that resolve to a private network range 
( tried by adding some local adddress to the DNS of my domain name )
