### ISSUE TITLE
Document using EventStore Cloud with GKE

### ISSUE THREAD

**Issue by oskardudycz** [kurrent-io/documentation#257]
https://docs.google.com/document/d/1td5jDnsdom2T4-4i09NZ_AvOVM1b5S9UDVWPBO-KEQA/edit?usp=sharing

**Comment by ylorph** [comment]
@alexeyzimarev , @oskardudycz  text is ok for me.
How do we publish this ? Doc / blog ?

**Comment by oskardudycz** [comment]
@ylorph I think that we can start with Blog, but I think this should eventually (asap) get into the docs. Especially that the style and narrative of this post are more How-To than a traditional blog post.
