### ISSUE TITLE
Cloud : add complete walkthroughs

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#270]
creating a complete cluster + stuff in the customer cloud 
- for all 3 clouds
- for all 3 methods (console, terraform, esc)
- from scratch (EsDb cloud & customer cloud )

**Comment by mat-mcloughlin** [comment]
Make sure we document the other side of the VPC for the various cloud providers as well

**Comment by ylorph** [comment]
Check completeness / guide ?
