### ISSUE TITLE
eventstore command not found

### ISSUE THREAD

**Issue by diegosasw** [kurrent-io/documentation#280]
Following the instructions on how to install for Linux there is a step to check the version https://developers.eventstore.com/server/v20/server/configuration/#version-and-help

but eventstore is not available as a command: `eventstore: command not found`

It is installed though, awaiting to make changes in the configuration so that it can start.
```
systemctl | grep eventstore
eventstore.service                               loaded failed failed    EventStoreDB Server
```

For Linux newbies (and to improve docs), which step is missing in order to have the command eventstore available in CLI? If modifying the `$PATH` is required, where should it point to?

PS: I don't see where else could it be the "executable"
```
#whereis eventstore
eventstore: /etc/eventstore /usr/share/eventstore
```

**Comment by alexeyzimarev** [comment]
The name of the executable is `eventstored`. The service is installed, but not started, as we mentioned on the Installation - Linux page:

> When you install the EventStoreDB package, the service doesn't start by default. It's done to allow you to change the configuration, located at /etc/eventstore/eventstore.conf and to prevent creating database and index files in the default location.

Please don't run the executable from your user account with `--what-if` option as it will create data and logs directories owned by your user and the service will then fail to start.

**Comment by oskardudycz** [comment]
@diegosasw I deployed @alexeyzimarev changes made in https://github.com/EventStore/documentation/issues/280. Could you check if now documentation is more straightforward for you?
I'm closing the issue, but feel free to comment if you have more concerns than reopen it.
