### ISSUE TITLE
remove single vpc peering warning for GCP

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#292]
https://github.com/EventStore/documentation/blob/master/docs/cloud/provision/gcp/README.md#network-peering
peering limits on gcp:
https://cloud.google.com/vpc/docs/quota#vpc-peering

**Comment by mat-mcloughlin** [comment]
::: warning Peering limitations Currently, you can peer one Event Store Cloud network with only one GCP network on your account. We expect to lift this limitation in the future. :::
