### ISSUE TITLE
PreferSlaveNode() and PreferRandomNode() missing from TCP client documentation

### ISSUE THREAD

**Issue by shaan1337** [kurrent-io/documentation#293]
The node preference section in the client docs is not accurate:
https://developers.eventstore.com/clients/dotnet/5.0/connecting/options.html#node-preference

PerformOnMasterOnly() and PerformOnAnyNode() option are used to allow forwarding of operations from slave/follower to master/leader instead of forcing the client to connect to the master/leader.

In addition to PerformOnAnyNode(), PreferSlaveNode() should be used to give priority to connect to slave nodes first (or PreferRandomNode() to connect to any node). If not set, the default behaviour is to connect to the master/leader.

These options cannot currently be set via connection string: https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/issues/74

**Comment by mat-mcloughlin** [comment]
Just coming back to this @shaan1337 do you want to submit a PR for it please
