### ISSUE TITLE
Internal links show 404 page when opened in separate tab/window.

### ISSUE THREAD

**Issue by rmfaheem** [kurrent-io/documentation#315]
## Behaviour
Links to other parts of the documentation show a 404 page.
This behaviour occurs only when they are opened in a new tab or a new window.

The strange issue is that on the first load, it shows a 404 page. But after a refresh, the correct page is shown.

Example link: https://developers.eventstore.com/server/v5/docs/server/introduction/clients.html

Before refresh:
![image](https://user-images.githubusercontent.com/51624008/112603844-f7aecd00-8e2e-11eb-8b3c-177f63c62f9c.png)

After refresh:
![image](https://user-images.githubusercontent.com/51624008/112603898-07c6ac80-8e2f-11eb-86ec-b012a0bbfc84.png)

All external links seem to work fine.

## Expected behaviour
Show the correct page.

## Browser
Chrome Version 89.0.4389.90 (Official Build) (64-bit)
FireFox 87.0 (64-bit)

**Comment by alexeyzimarev** [comment]
Thanks for reporting, we are aware of the issue. It is caused by a massive restructure we are currently doing with the docs. We expect things to stabilise in a few days.

**Comment by alexeyzimarev** [comment]
Btw I cannot see this issue now. When I open the link you mentioned, it shows the page properly.

**Comment by alexeyzimarev** [comment]
Also tried Firefox, works fine.

**Comment by rmfaheem** [comment]
Yes, for some reason, I seem to be the only one facing this.
I tried clearing the cache but it's not that.

Definitely an unusual thing.

Hopefully, it's not something that's related to a CDN or anything that's out of our control.
