### ISSUE TITLE
Document / sample "subscription is not event receiving the very first event "

### ISSUE THREAD

**Issue by ylorph** [kurrent-io/documentation#325]
https://developers.eventstore.com/clients/grpc/subscribing-to-streams/#subscribing-from-a-specific-position

when subscribing to a stream / $all using from the beginning `StreamPosition.Start`, it is not very clear that you will miss the very first event , because the from is exclusive.

we should add a small section with a sample , something like @alexeyzimarev  did here :
https://github.com/alexeyzimarev/EventStore.Subscriptions/blob/0a60f8bcb736b6b53bcb2d8bd0a3bdf7062de1d6/src/EventStore.Subscriptions/StreamSubscriptionService.cs#L38

**Comment by mat-mcloughlin** [comment]
closing this as it will either be fixed or documented as part of the https://github.com/EventStore/architecture-and-planning/issues/33 RFC
