### ISSUE TITLE
Add warning about using the server generate timestamp

### ISSUE THREAD

**Issue by mat-mcloughlin** [kurrent-io/documentation#339]

**Comment by ylorph** [comment]
https://github.com/ylorph/The-Inevitable-Event-Centric-Book/issues/42

**Comment by kijanawoodard** [comment]
Because the server time might "time travel" backwards?

**Comment by alexeyzimarev** [comment]
No, because you can replicate data to another server as part of some migration, and all the events will be "new" again.
