### ISSUE TITLE
Document dirty read behaviour

### ISSUE THREAD

**Issue by mat-mcloughlin** [kurrent-io/documentation#348]
In response to Freshdesk Issue 109634

=> " Dirty read", writing to leader , is acked , but reading from a follower => might not be indexed replicated yet so they think they "lost" an event which is not replicatd yet to that specific node (might be busy in recovering, doing somethting else ...)

**Comment by timothycoleman** [comment]
Just a comment on terminology, I think a 'dirty read' is when the system has allowed you to read data that is not yet committed

In the scenario above the problem seems to be not being able to read something that is committed

**Comment by mat-mcloughlin** [comment]
@ylorph can you give a more detailed explanation please
