### ISSUE TITLE
Create article/resource page in developers.eventstore.com

### ISSUE THREAD

**Issue by mat-mcloughlin** [kurrent-io/documentation#350]
Included an improve the eventsourcing and projection blog posts as part of this.

**Comment by mat-mcloughlin** [comment]
Looks good, need to think about what to do about release notes. Possibly adding it to the menu under server

Also we need an execise to go through all our existing blog posts and pull them into the resources

**Comment by mat-mcloughlin** [comment]
We also need to speak to @danjamescrosby about what to do with duplicated content as far as SEO is concerned

**Comment by danjamescrosby** [comment]
@mat-mcloughlin 

If we're linking directly to a post on the main blog that's fine, doesn't need anything extra doing from an SEO point of view.

If we're duplicating a post that's on the main blog, we just need to add a canonical link in the head section of the new page that points to the original. Like this: `<link rel="canonical" href="https://www.eventstore.com/blog/snapshots-in-event-sourcing" />`. From a user perspective, it doesn't change anything - it's great that someone using the docs can find and read the post on the developers site. From an SEO perspective, it just makes sure we prioritise the main website/blog for search engine rankings which I think is what we want.
