### ISSUE TITLE
Align persistent subscription start position

### ISSUE THREAD

**Issue by alexeyzimarev** [kurrent-io/documentation#351]
Seems like different clients have different default for the persistent subscription starting position. For .NET client it seems to be worse as it uses stream end, which makes it impossible to subscribe from the beginning of the stream, as by supplying 0 as the start position, we get events from 1.

**Comment by oskardudycz** [comment]
That should be covered in https://github.com/EventStore/home/pull/550/files#diff-ad3a37ec8a5416ddcd905109248d13dba6a72a352ce7ee41b9d3d004aae1ff95R38. Closing as duplicate.
