### ISSUE TITLE
Settings not listed in the what-if should not be included in the public documentation

### ISSUE THREAD

**Issue by condron** [kurrent-io/documentation#353]
Internal settings like EVENTSTORE_COMMIT_COUNT and EVENTSTORE_PREPARE_COUNT
should never be changed or set by users, and should not therefore be exposed in the public documentation.

For example changing these fundamentally alter the operation and guarantees of the database as advertised.
Further we have no tests or QA process in place to validate the system would work correctly if they are changed.

Reading the source code to find them and understand what they do is a minimum requirement for usage.

**Comment by mat-mcloughlin** [comment]
Adding this to the backlog @condron. If you get chance to create PR for it that would be appreciated

**Comment by mat-mcloughlin** [comment]
Closing as we aren't going to get to this any time soon
