### ISSUE TITLE
Extend gRPC client docs with information around Link, OriginalEvent, ResolvedEvent

### ISSUE THREAD

**Issue by mat-mcloughlin** [kurrent-io/documentation#432]
Look to RFC

**Comment by mat-mcloughlin** [comment]
@ylorph can you please link to the RFC that contains the information

**Comment by ylorph** [comment]
EventStore/architecture-and-planning/pull/9/

**Comment by mat-mcloughlin** [comment]
Closing as being addressed by another issue ^
