### ISSUE TITLE
Extend documentation to include places that we cannot guarantee idempotent

### ISSUE THREAD

**Issue by tambeau** [kurrent-io/documentation#465]
Presently, it seems as Idempotence cannot be guarantee after a server is restarted unless appropriate settings are set upon restart. We need to update the documentation for each client to reflect this and provide guidance as to what settings to use. 

See:
https://developers.eventstore.com/clients/dotnet/5.0/appending.html#optimistic-concurrency
https://developers.eventstore.com/clients/dotnet/5.0/appending.html#idempotence
https://eventstore.freshdesk.com/a/tickets/110012

**Comment by tambeau** [comment]
In the ticket 110012 the user asked as a follow up the question "Where else can this become an issue".
https://eventstore.freshdesk.com/helpdesk/tickets/110012

**Comment by mat-mcloughlin** [comment]
We need to add documentation about how the idempotency works on the server. This includes where it might not be guaranteed such as: 
- high ingress where the rolling cache isn't large enough 
- if the server restarts causing the cache to be lost as it's not rebuilt on startup
