### ISSUE TITLE
Missing code samples in `Appending events` page.

### ISSUE THREAD

**Issue by SinghCoder** [kurrent-io/documentation#506]
Hey there, I stumbled across the website documentation, and on `Appending events` page, was checking code samples and found they are missing for `Go`, `Java` and `Typescript`, and the message says `File not found!`. Hoping this is not what you expected. If the samples are not available, probably a better message might be `Code sample not available currently! Coming Soon!!` or something.

Attaching screenshots of what it looks lik:

## Typescript

![ts](https://user-images.githubusercontent.com/32142363/152950769-3a212a79-8a55-46ae-9836-979089fef240.png)

## Java

![java](https://user-images.githubusercontent.com/32142363/152950774-65c41969-655e-4eae-ad38-bd8a1d911ccc.png)

## Go

![go](https://user-images.githubusercontent.com/32142363/152950781-8bf06292-b00b-4593-900c-3edec0f62736.png)

**Comment by alexeyzimarev** [comment]
Thank you for reporting, it's fixed in a branch. We will merge it soon.

**Comment by oskardudycz** [comment]
That's fixed, now 👍 We apologize for the inconvenience.

**Comment by SinghCoder** [comment]
Thanks so much for quick response @alexeyzimarev  and @oskardudycz !!
