### ISSUE TITLE
Getting System.NullReferenceException when Persistent Subscription gets a deleted event 

### ISSUE THREAD

**Issue by lakshdeepsingheventstore** [kurrent-io/documentation#555]
When a Persistent Subscription is created on a stream, events are buffered. Now, if the deleted event has already been buffered, that is the event was sent to the Persistent subscription before that event was deleted, you will get that event processed by the client and will get the exact same event body.
If in case the deleted event was not buffered, in that case you will get a null object for such non buffered, deleted events.
This could be mentioned in the documentation.

Internal Ticket : https://eventstore.freshdesk.com/a/tickets/110452

**Comment by alexeyzimarev** [comment]
Not a documentation issue
