### ISSUE TITLE
Improve Documentation Around System Defaults

### ISSUE THREAD

**Issue by rmfaheem** [kurrent-io/documentation#559]
We need clearer guidelines around how system defaults should be tuned for eventstore. One example is the LimitNOFILE parameter on Linux, which we recommend should be increased to a ['high number'](https://developers.eventstore.com/server/v21.10/installation.html#install-from-packagecloud)

I believe the documentation should have clearer guidelines on these types of defaults, and maybe include them in a section of their own so that they are not glossed over.

<sub>[DOC-142](https://linear.app/eventstore/issue/DOC-142/improve-documentation-around-system-defaults)</sub>

**Comment by lakshdeepsingheventstore** [comment]
If possible, we should also conduct some tests to propose values for critical/production usage of ESDB.
